import { useEffect, useState } from 'react'
import { deleteInvoice, errorMessage, getInvoices, isAuthError } from '../services/api'
import { Empty, ErrorState, Loading, Toast } from '../components/Feedback'
import Modal from '../components/Modal'
import { useAuth } from '../auth/AuthContext'
import { useNavigate } from 'react-router-dom'

const money = (value) => `Rs ${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const date = (value) => value ? new Date(value).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '-'
const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3000'

export default function Invoices() {
  const [invoices, setInvoices] = useState([]); const [total, setTotal] = useState(0); const [search, setSearch] = useState(''); const [startDate, setStartDate] = useState(''); const [endDate, setEndDate] = useState(''); const [selected, setSelected] = useState(null); const [confirming, setConfirming] = useState(null); const [toast, setToast] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const { signOut } = useAuth(); const navigate = useNavigate()
  async function load() { setLoading(true); setError(''); try { const data = await getInvoices({ ...(search && { search }), ...(startDate && { startDate }), ...(endDate && { endDate }) }); setInvoices(data.invoices || []); setTotal(data.totalAmount || 0) } catch (err) { if (isAuthError(err)) { signOut(); navigate('/login') } else setError(errorMessage(err, 'Unable to load invoices.')) } finally { setLoading(false) } }
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer) }, [search, startDate, endDate])
  async function remove() { try { await deleteInvoice(confirming.id); setConfirming(null); setToast({ message: 'Invoice deleted successfully.' }); await load() } catch (err) { setToast({ message: errorMessage(err, 'Unable to delete invoice.'), type: 'error' }) } }
  return <div className="content-stack"><div className="page-intro"><div><p className="eyebrow">Records</p><h2>Invoice management</h2><p className="muted">Review every invoice submitted by your team.</p></div><div className="total-chip"><span>Filtered total</span><strong>{money(total)}</strong></div></div><section className="panel"><div className="filter-bar"><label className="search-field"><span>Search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Title, vendor, category..." /></label><label><span>From</span><input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label><span>To</span><input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label><button className="button button-secondary filter-clear" onClick={() => { setSearch(''); setStartDate(''); setEndDate('') }}>Clear</button></div>{loading ? <Loading /> : error ? <ErrorState message={error} onRetry={load} /> : invoices.length ? <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Vendor</th><th>Added by</th><th>Invoice date</th><th>Created</th><th className="align-right">Amount</th><th /></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id}><td><button className="table-link" onClick={() => setSelected(invoice)}><strong>{invoice.title}</strong><span className="table-sub">{invoice.category}</span></button></td><td>{invoice.vendor}</td><td>{invoice.user_name || 'Unknown'}</td><td>{date(invoice.invoice_date)}</td><td>{date(invoice.created_at)}</td><td className="align-right amount">{money(invoice.amount)}</td><td><button className="danger-link" onClick={() => setConfirming(invoice)}>Delete</button></td></tr>)}</tbody></table></div> : <Empty title="No invoices found" subtitle="Try changing the search or date filters." />}</section>{selected && <InvoiceDetails invoice={selected} close={() => setSelected(null)} />}{confirming && <Modal title="Delete invoice?" onClose={() => setConfirming(null)}><p className="modal-copy">This will remove <strong>{confirming.title}</strong> from the invoice records. This action cannot be undone.</p><div className="modal-actions"><button className="button button-secondary" onClick={() => setConfirming(null)}>Cancel</button><button className="button button-danger" onClick={remove}>Delete invoice</button></div></Modal>}<Toast {...toast} onClose={() => setToast(null)} /></div>
}

function InvoiceDetails({ invoice, close }) { return <Modal title="Invoice details" onClose={close} wide><div className="detail-layout"><div className="invoice-preview">{invoice.image_url ? <img src={`${apiUrl}${invoice.image_url}`} alt={`Invoice ${invoice.title}`} /> : <span>No image attached</span>}</div><div className="detail-list"><Detail label="Title" value={invoice.title} /><Detail label="Vendor" value={invoice.vendor} /><Detail label="Amount" value={money(invoice.amount)} /><Detail label="Category" value={invoice.category} /><Detail label="Invoice date" value={date(invoice.invoice_date)} /><Detail label="Created" value={date(invoice.created_at)} /><Detail label="Added by" value={invoice.user_name || 'Unknown'} /><Detail label="Description" value={invoice.description || 'No description'} /></div></div></Modal> }
function Detail({ label, value }) { return <div className="detail-row"><span>{label}</span><strong>{value}</strong></div> }