import { useEffect, useState } from 'react'
import { createUser, errorMessage, getUsers, isAuthError } from '../services/api'
import { Empty, ErrorState, Loading, Toast } from '../components/Feedback'
import Modal from '../components/Modal'
import { useAuth } from '../auth/AuthContext'
import { useNavigate } from 'react-router-dom'

export default function Users() {
  const [users, setUsers] = useState([]); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ username: '', password: '', role: 'user' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [formError, setFormError] = useState(''); const [toast, setToast] = useState(null)
  const { signOut } = useAuth(); const navigate = useNavigate()
  async function load() { setLoading(true); setError(''); try { setUsers(await getUsers()) } catch (err) { if (isAuthError(err)) { signOut(); navigate('/login') } else setError(errorMessage(err, 'Unable to load users.')) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function submit(event) { event.preventDefault(); setFormError(''); if (!form.username.trim() || !form.password) return setFormError('Username and password are required.'); setSaving(true); try { await createUser({ ...form, username: form.username.trim() }); setForm({ username: '', password: '', role: 'user' }); setShowForm(false); setToast({ message: 'User created successfully.' }); await load() } catch (err) { setFormError(errorMessage(err, 'Unable to create user.')) } finally { setSaving(false) } }
  const visible = users.filter((user) => user.username.toLowerCase().includes(search.toLowerCase()))
  return <div className="content-stack"><div className="page-intro"><div><p className="eyebrow">Directory</p><h2>User management</h2><p className="muted">Manage the accounts that can submit invoices.</p></div><button className="button button-primary" onClick={() => { setFormError(''); setShowForm(true) }}>+ Add user</button></div><section className="panel"><div className="panel-toolbar"><label className="search-field"><span>Search users</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by username..." /></label><span className="result-count">{visible.length} of {users.length} users</span></div>{loading ? <Loading /> : error ? <ErrorState message={error} onRetry={load} /> : visible.length ? <div className="table-wrap"><table><thead><tr><th>Username</th><th>User ID</th><th>Role</th></tr></thead><tbody>{visible.map((user) => <tr key={user.id}><td><strong>{user.username}</strong></td><td>#{user.id}</td><td><span className={`role-badge role-${user.role}`}>{user.role}</span></td></tr>)}</tbody></table></div> : <Empty title="No matching users" />}</section>{showForm && <Modal title="Create a user" onClose={() => !saving && setShowForm(false)}><form className="form-stack" onSubmit={submit}><label>Username<input value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} autoComplete="off" /></label><label>Password<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} autoComplete="new-password" /></label><label>Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="user">User</option><option value="admin">Admin</option></select></label>{formError && <div className="inline-error">{formError}</div>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setShowForm(false)} disabled={saving}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? 'Creating...' : 'Create user'}</button></div></form></Modal>}<Toast {...toast} onClose={() => setToast(null)} /></div>
}